<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<AssemblyName>Projects</AssemblyName>
		<RootNamespace>Projects</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Capsitech" Version="0.6.9" />
	<PackageReference Include="Cronos" Version="0.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.5" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="8.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Identity\" />
  </ItemGroup>

</Project>
